### ISSUE TITLE
老兄，能再细心点吗

### ISSUE THREAD

**Issue by dashankeji** [jiangzhenfei/wx2toutiao#1]
ttml有引入其他模板文件的  <import src ="../header.wxml" />   一律被你保持原样，我寻思文件都被转成  header.ttml  了，哪里还找得到  header.wxml  啊？

同样的问题，ttss有引入其他样式文件的  @import "colorui.wxss";   一律被你保持原样，我寻思文件都被转成  colorui.ttss  了，哪里还找得到  colorui.wxss  啊？

**Comment by jiangzhenfei** [comment]
sorry啊，写的时候头条还在内测，转过之后改了很多才运行起来，导致忘记改这些细节了
